
drop table if exists Person;

drop table if exists Book;

create table if not exists Person(
    id int GENERATED BY DEFAULT AS IDENTITY ,
    name varchar unique,
    year int

);

create table if not exists Book(
    id int GENERATED BY DEFAULT AS IDENTITY ,
    name varchar,
    author varchar,
    year int
);

INSERT INTO Book(name,author,year) VALUES('Над пропастью во ржи','Джером Сэлинджер', 1951);
INSERT INTO Book(name,author,year) VALUES('День опричника','Владимир Сорокин', 2006);
INSERT INTO Book(name,author,year) VALUES('Тайные виды на гору Фудзи','Владимир  Пелевин', 2018);
INSERT INTO Book(name,author,year) VALUES('Философия Java','Брюс Эккель', 2018);


