
drop table if exists Book;
drop table if exists Person;

create table if not exists Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    name varchar unique,
    year int
);

create table if not exists Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar,
    author varchar,
    year int,
    person_id int REFERENCES person(id) ON DELETE SET NULL
);

INSERT INTO Book(name,author,year) VALUES('Над пропастью во ржи','Джером Сэлинджер', 1951);
INSERT INTO Book(name,author,year) VALUES('День опричника','Владимир Сорокин', 2006);
INSERT INTO Book(name,author,year) VALUES('Тайные виды на гору Фудзи','Владимир  Пелевин', 2018);
INSERT INTO Book(name,author,year) VALUES('Философия Java','Брюс Эккель', 2018);
INSERT INTO Book(name,author,year) VALUES('Психопатология обыденной жизни','Зигмунд Фрейд', 1904);
INSERT INTO Book(name,author,year) VALUES('Игра в Бисер','Герман Гессе', 1943);
INSERT INTO Book(name,author,year) VALUES('Бытие и время','Мартин Хайдигер', 1927);

INSERT INTO Person(name,year) VALUES('Иванов Иван', 1986);
INSERT INTO Person(name,year) VALUES('Петров Петр', 2009);
INSERT INTO Person(name,year) VALUES('Федор Сумкин', 1999);

